project:
  type: website
  output-dir: docs

website:
  title: "Picture-Word Verification Poster"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - abstract.qmd
      - text: "Poster"
        file: "poster.pdf"
      - stimuli.qmd
      - localiser.qmd
      - text: "Preregistration"
        file: "https://osf.io/jk3r4"
      - text: "Data and Code"
        file: "https://osf.io/389ce/"
      - text: "Preprint"
        file: "https://doi.org/10.1101/2023.08.07.552265"

format:
  html:
    theme:
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true
    mainfont: "Arial"

editor: visual

