project:
  type: website
  output-dir: docs

website:
  title: "Picture-Word Verification Poster"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: "Abstract"
      - text: "Poster"
        file: "poster.pdf"
      - text: "Preprint"
        file: "https://doi.org/10.1101/2023.08.07.552265"
      - text: "OSF"
        file: "https://osf.io/389ce/"
      - text: "Preregistration"
        file: "https://osf.io/jk3r4"
      - sidebar:details
    
  sidebar:
    - id: details
      title: "More"
      contents:
        - stimuli.qmd
        - localiser.qmd

format:
  html:
    theme:
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true
    mainfont: "Arial"
    sidebar: false

editor: visual

