---
title: "Abstract"
toc: false
---

Predictive coding models posit that brain activity scales with prediction error: the difference between ascending (bottom-up) input and descending (top-down) predictions. Prediction error captures two key variables: *magnitude* and *certainty* of the ascending-descending difference. Greater violations of expectations should elicit greater prediction error signals, and this effect should become larger as certainty increases. We asked whether such a simple predictive coding account could describe neural activity indexed by the N1 (~170 ms) event-related potential component elicited by words. Indeed, findings have shown that the word-related N1 is sensitive to predictions, with unpredicted words generally eliciting greater-amplitude N1s than predicted words. However, effects of error magnitude and certainty have mostly been investigated in isolation, providing incomplete tests of predictive coding. In our pre-registered study, we tested the account via the interaction between prediction congruency (error magnitude) and predictability (certainty). We recorded electroencephalograms for 68 participants while they completed a picture-word verification paradigm. PICTURE-*word* pairs were congruent (e.g., ONION-*onion*) or incongruent (e.g., ONION-*torch*), while predictability was manipulated continuously based on norms of picture-name association (% name agreement). Pre-registered analyses failed to find evidence that the direction of the congruency-predictability interaction matched that expected under a simple predictive coding account. Exploratory Bayesian analyses found strong evidence against the account, with the congruency-predictability interaction 59.98 times more likely in the opposite direction. Specifically, higher predictability elicited *larger* N1s for *picture-congruent* words, and *smaller* N1s for *picture-incongruent* words. We argue that a simple predictive coding account of the N1 is either incorrect or requires elaboration.